language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - yarn
  - yarn build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_S3_BUCKET_NAME
  local_dir: build
  on:
    branch: "develop"